API/API/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from Plan.views import Plan

router = routers.DefaultRouter()
router.register('Plan', Plan, basename='Plan')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include((router.urls, 'Plan'), namespace='Plan')),
]


# for url in router.urls:
#     print(url)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

API/home/urls.py
from django.urls import path
from .views import home, download_apk
app_name = 'home'

urlpatterns = [
    path('home/', home, name='home'),
    path('download/', download_apk, name='download'),
]

API/home/models.py
from django.db import models


class Apk(models.Model):
    version = models.CharField(unique=True, max_length=100)
    release_date = models.DateField(blank=True, null=True)
    apk = models.FileField(upload_to='apk')

    def __str__(self):
        return f'WatPlan {self.version}'

    class Meta():
        ordering = ['release_date']


class Data(models.Model):
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=1000)


class ReleaseNote(models.Model):
    apk = models.ForeignKey(Apk, on_delete=models.CASCADE,
                            related_name='release_notes')
    content = models.CharField(max_length=300)

    def __str__(self):
        return f'Release note {self.apk.version}'

API/home/views.py
from django.shortcuts import render, redirect
from django.utils.encoding import smart_str
from django.http import HttpResponse

from .models import Apk


def home(request, *args, **kwargs):
    apks = Apk.objects.all().order_by('-release_date')
    context = {
        'apks': apks,
    }
    return render(request, 'home/home.html', context)


def download_apk(request, *args, **kwargs):
    apk = Apk.objects.all().order_by('-release_date').first().apk
    file_name = apk.name.split('/')[-1]
    file = apk.file
    response = HttpResponse(file, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename={smart_str(file_name)}'
    response['X-Sendfile'] = smart_str(apk.name)
    return response

API/home/templates/home/home.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Raleway:800,900|&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/home.css'%}">


    <title>Wat Plan</title>
</head>


<body>
    <nav>
        <div class="logo">
            <img src="{%static 'home/images/logo.png'%}" alt="logo">
        </div>
    </nav>
    <div class="divider"> </div>
    <main>
        <div>
            <a href="{%url 'home:download'%}">
                <button>
                    <p>DOWNLOAD APK</p>
                    <img src="{%static 'home/images/android-head-icon.png'%}" alt="android">
                </button>
            </a>
        </div>
        {% for apk in apks %}
        <div class="apk-version">
            <div class="apk-info">
                <p class="apk-name">
                    {{apk}}
                </p>
                <p class="apk-date">
                    {{apk.release_date}}
                </p>
            </div>

            <div class="release-notes">
                {% for note in apk.release_notes.all%}
                <p class="release-note">
                    • {{note.content}}
                </p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </main>

</body>

</html>